### ISSUE TITLE
Why is WebDAV not sufficient

### ISSUE THREAD

**Issue by bslassey** [dimmyvi/tigress-requirements#23]
This question was asked at IETF 114 and should be addressed in the [Review of existing solutions](https://github.com/dimmyvi/tigress-requirements/blob/main/draft-tigress-requirements.md#review-of-existing-solutions)

**Comment by castiz** [comment]
Looking at the comments, I think @ekr suggested this. Eric, what part of the solution were you envisioning replacing with webDAV? I wasn't sure if you're thinking of replacing the relay server or some other element.

**Comment by ekr** [comment]
Yes, my question was why the relay server can't simply be a profile of WebDAV.

**Comment by castiz** [comment]
In theory, we could rewrite the solution to use WebDAV. Some of the functionality matches, like the lock & unlock verbs. WebDAV isn’t widely supported by Web Frameworks out of the box so it seems like an extra barrier to entry for implementing a solution and would reduce the number of entities that would adopt a standard. Could you elaborate more on where you see the benefits of adding WebDAV to this solution?

**Comment by ekr** [comment]
Sure. It provides pre-existing functionality that you would otherwise have to invent.

**Comment by castiz** [comment]
In my opinion, the main reason not to use it is because it is not widely supported by web frameworks. We want to make sure there are limited barriers to entry, and use widely accepted technologies. I'd love to hear other's thoughts here though. @bslassey @nicksha  what do you think?

**Comment by ekr** [comment]
What do you mean "by Web frameworks"? For instance, which frameworks?

**Comment by bslassey** [comment]
I have the same question as to what you mean by "web frameworks" here. There are certainly many implementations of WebDAV in existence already, so I would be in favor or reusing existing tech rather than inventing new things.

**Comment by castiz** [comment]
Sorry maybe I didn't use the best wording. So if we used webDAV instead of an intermediary server, wouldn't both iOS devices and Android (etc) need to support webDAV? I am pretty sure iOS does not already, and based on my limited knowledge it doesn't seem Android does either. I see there are some webDAV apps, but presumably the credential management app would need to use webDAV in some capacity. 

Let me know if you were envisioning something else and I'm not understanding?

**Comment by dimmyvi** [comment]
Hi Eric, thanks for clarifying the question. While the solution to the problem can be implemented in a number of ways, including, but not limited to, WebDAV, S3, Signal, etc, we believe that the complexity of implementation for the particular problem that we had, would be much higher if we chose other protocols.

**Comment by bslassey** [comment]
@castiz from some quick google searching, it seems supporting WebDAV with existing Android APIs is relatively strait forward.

@dimmyvi  I think you overstate the complexity of an implementation using WebDAV. 

But, at a higher level, for this document we're describing the requirements and why various existing technology doesn't meet them. From everything I've read here so far, WebDAV is a perfectly valid option.

**Comment by ekr** [comment]
> But, at a higher level, for this document we're describing the requirements and why various existing technology doesn't meet them. From everything I've read here so far, WebDAV is a perfectly valid option.

I think this last sentence is the main point. It seems to me that this document should largely stick to the requirements on existing technologies.

**Comment by dimmyvi** [comment]
I can agree with the statement, that requirements should stick to what the system needs. Bringing it to review with the community is certainly more coming for an advice, not dictating the technology to solve the problem.
If someone makes an effort to propose an implementation involving other technologies than we proposed in Tigress, that better align with the requirements, this certainly should be reviewed and considered.

**Comment by dimmyvi** [comment]
alternative solutions, including webdav are in scope for tigress - a new requirements document with sample implementation based on WedDAV was published on 17 Feb
