### ISSUE TITLE
How is Signal different than WhatsApp (or other generic messaging systems)?

### ISSUE THREAD

**Issue by bslassey** [dimmyvi/tigress-requirements#25]
https://github.com/dimmyvi/tigress-requirements/blob/main/draft-tigress-requirements.md#signal-protocol

**Comment by castiz** [comment]
I think in this section we were trying to specify the Signal protocol specifically rather than the Signal App. The Signal App is the same as WhatsApp I believe but using the protocol outside the app is what we were trying to address.

**Comment by dimmyvi** [comment]
We are just answering questions asked in IETF 114 by Eric Rescorla - he specifically mentioned signal.

**Comment by bslassey** [comment]
> We are just answering questions asked in IETF 114 by Eric Rescorla - he specifically mentioned signal. You're right, it does not really matter what protocol can be used as an alternative, it still doesn't satisfy the requirements the way we put it - separation of channels.

I think @ekr also asked about WhatsApp, SMS and others at the mic as well and it is important to be able to answer questions about individual messaging platforms/protocols. But in the document we should be describing the characteristics of a class of solutions. I can't tell from the text right now what is different about Signal such that it is addressed separately from other generic messaging platforms or what characteristics would cause other platforms to be addressed by the same reasoning.

**Comment by ekr** [comment]
Yeah, it was just an example. Like "I have a secure messaging system...."

**Comment by castiz** [comment]
We can remove it from its own section if that would be better? And include it in the messaging app section.

**Comment by dimmyvi** [comment]
With the latest change in the requirements draft, are we ok to close this issue?

**Comment by dimmyvi** [comment]
this was addressed in the general version of the requirements doc published on 17 Feb + sample impl docs. I thin we can close this issue
