### ISSUE TITLE
Why should the user not be able to see the data if they want to?

### ISSUE THREAD

**Issue by bslassey** [dimmyvi/tigress-requirements#7]
> This data SHOULD never be visible to said user in whichever messaging application the sender chose to initiate the transfer on. This eliminates the possibility of merely sending the requisite data inline, through an SMS or email for example, rather than leveraging an Intermediary server.

Why should the user not be able to see the data if they want to?

**Comment by dimmyvi** [comment]
here we tried to say that the provisioning data itself won't be sent over whatever email/messaging app uses choses. This data will be temporary stored on Relay server and the link to the content stored there will be sent over SMS/email etc.

**Comment by dimmyvi** [comment]
ack

**Comment by dimmyvi** [comment]
Per  #11 we agreed to dismiss the requirement of separation of provisioning information and URL link
