### ISSUE TITLE
Is disallowing group sharing a goal?

### ISSUE THREAD

**Issue by bslassey** [dimmyvi/tigress-requirements#8]
> (Req-P2P) A credential transfer SHALL be strictly from one device to another (group sharing is not a goal).
There is a difference between group sharing not being a goal and it being a goal to not allow group sharing. As I read this line it says the latter thing first and the former thing second. Which is intended?

**Comment by dimmyvi** [comment]
eh, it's the former, we wanted to limit the scope to just peer-to-peer sharing (even though this may be a base for B2P in the future). Agree, this needs to be adjusted for clarity

**Comment by dimmyvi** [comment]
Hope that https://github.com/dimmyvi/tigress-requirements/pull/10 has addressed this issue
