### ISSUE TITLE
Req-security is unclear

### ISSUE THREAD

**Issue by bslassey** [dimmyvi/tigress-requirements#9]
> (Req-Security) Solution SHOULD provide security of the provisioning data transferred (MITM, brute-force attacks on the content, DDOS attacks etc).

It is unclear to me what this requirement is trying to say. What are the threats we're trying to protect against?

**Comment by dimmyvi** [comment]
Protect content in transit on relay server - confidentiality (encrypt content stored on relay), integrity (impersonation attacks by storing malicious content - protect by device attestation at the time of creation) and availability - introduce measures against denial of service - protect the webapp on the network level.

**Comment by dimmyvi** [comment]
This may came a bit vague, if you could suggest a better wording, it would be very much appreciated!

**Comment by bslassey** [comment]
@dimmyvi do you have a threat model document that we can work off of here?

**Comment by dimmyvi** [comment]
Yes, we have a review tomorrow with security team and will publish it - probably in a day. Will add a link to it here.

**Comment by bslassey** [comment]
Thanks, I look forward to reading it.

**Comment by dimmyvi** [comment]
We added a threat model draft: https://github.com/dimmyvi/tigress-sample-implementation/blob/main/draft-tigress-sample-implementation.md

**Comment by dimmyvi** [comment]
Hi Brad, I finished updating the threat model document, planning to publish it tomorrow (5 November) on Datatracker.
If you could review and provide feedback, I'd very much appreciate it

**Comment by bslassey** [comment]
I don't think publishing the security model resolves this, but it is an important step in getting a shared understanding of the security requirements such that they can be described accurately in this doc.

Apologies for not being able to review the security model yet, it is on my to-do list.

**Comment by dimmyvi** [comment]
this was addressed in a new requirements document with sample implementations was published on 17 Feb. We can close the issue
